server:
  port: 8101
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 启用自动根据服务ID生成路由
          lower-case-service-id: true # 设置路由的路径为小写的服务ID
      routes: #配置路由路径
        - id: seed-auth
          uri: lb://seed-auth
          predicates:
            - Path=/seed-auth/**
          filters:
            - StripPrefix=1 # 移除前缀 seed-auth