#server:
#  port: 8101
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    gateway:
#      discovery:
#        locator:
#          enabled: true # 启用自动根据服务ID生成路由
#          lower-case-service-id: true # 设置路由的路径为小写的服务ID
#      routes: #配置路由路径
#        - id: seed-auth
#          uri: lb://seed-auth
#          predicates:
#            - Path=/auth/**
#          filters:
#            - StripPrefix=1 # 移除前缀 seed-auth
#secure:
#  ignore:
#    urls: #配置白名单路径
#      - "/actuator/**"
#      - "/auth/oauth/token"
#      - "/auth/oauth/hasPermission"
#      - "/auth/test/**"
spring:
  redis:
    lettuce:
      pool:
        max-active: 