#server:
#  port: 8103
#spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  datasource:
#    driver-class-name:  com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-test-query: SELECT 1
#      max-lifetime: 30000
#      maximum-pool-size: 15
#      minimum-idle: 3
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://127.0.0.1:3307/seed_project?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false
#    username: root
#    password: 123456
#  #redis 配置
#  redis:
#    database: 0
#    host: 127.0.0.1
#    lettuce:
#      pool:
#        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
#        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
#        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
#        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
#      shutdown-timeout: 100ms
#    password: ''
#    port: 6379
##mybatis plus 设置
#mybatis-plus:
#  mapper-locations: classpath*:com/demo/cody/**/xml/*Mapper.xml
#  global-config:
#    # 关闭MP3.0自带的banner
#    banner: false
#    db-config:
#      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
#      id-type: 4
#      # 默认数据库表下划线命名
#      table-underline: true
#  configuration:
#    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    # 返回类型为Map,显示null对应的字段
#    call-setters-on-nulls: true
##单Redis节点模式
#redisson:
#  #  password: ''
#  #      集群模式:SINGLE(单例),SENTINEL(哨兵),MASTERSLAVE(主从),CLUSTER(集群),REPLICATED(云托管)
#  model: SINGLE
#  #       单例模式参数
#  singleServerConfig:
#    address: 127.0.0.1:6379
#    database: 1